title: "postern"
description: "Amall door in a thick wall"
baseurl: ""
url: ""
context: "postern"
repo: "selfdriven-octo/postern"

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: selfdriven

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - _well-known/